[package]
name = "jq5"
version = "0.1.0"
edition = "2021"
description = "An extension of jq to work on JSON5 files, preserving comments"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "=4.5.23", features = ["derive"] }
clap_lex = "=0.7.4"
json5format = "0.2"
serde_json = "1"
serde_json5 = "0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "io-util"] }
futures = "0.3"

# Pin pest to versions compatible with rustc 1.82
pest = "=2.7.15"
pest_derive = "=2.7.15"
